apiVersion: v1
kind: Service
metadata:
  name: devopscloudcamp
  namespace: cloudru
spec:
  selector:
    app: devopscloudcamp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
